'use client';
import { useEffect, useRef } from 'react';
import { Download, FileText, X } from 'lucide-react';
import { useAdminDemo } from '../hooks/use-admin-demo';
import type { AdminDonation } from '../lib/admin-demo';
import { demoDonor, formatDonationAmount, formatDonationDate, type DemoDonation } from '../lib/account-demo';
function StatusBadge({status}:{status:DemoDonation['status']}){return <span className={`account-status account-status-${status.toLowerCase()}`}>{status}</span>;}
function PaymentBadge({method}:{method:AdminDonation['method']}){return <span className={`account-payment account-payment-${method==='PayPal'?'paypal':'bank'}`}>{method}</span>;}
function ReceiptAction({donation}:{donation:AdminDonation}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{const dialog=ref.current;return()=>{if(dialog?.open)dialog.close();};},[]);return <><button className="receipt-action" onClick={()=>ref.current?.showModal()}><Download aria-hidden="true"/>Download Receipt</button><dialog ref={ref} className="receipt-preview-dialog" aria-labelledby={`receipt-title-${donation.reference}`} onClick={e=>{if(e.target===ref.current)ref.current?.close();}}><section className="receipt-preview-panel"><button className="receipt-close" aria-label="Close receipt preview" onClick={()=>ref.current?.close()}><X aria-hidden="true"/></button><span className="receipt-preview-icon"><FileText aria-hidden="true"/></span><p className="eyebrow">Receipt availability</p><h2 id={`receipt-title-${donation.reference}`}>Receipt Preview</h2><p className="receipt-preview-copy">This completed contribution is eligible for a receipt. PDF receipts will be available when receipt services are connected. No PDF has been generated or downloaded.</p><dl className="receipt-preview-details"><div><dt>Reference</dt><dd>{donation.reference}</dd></div><div><dt>Donation for</dt><dd>{donation.givingFor}</dd></div><div><dt>Category</dt><dd>{donation.category}</dd></div><div><dt>Date</dt><dd>{formatDonationDate(donation.date)}</dd></div><div><dt>Contribution</dt><dd>{formatDonationAmount(donation.amountCents)}</dd></div></dl><button className="button receipt-dismiss" onClick={()=>ref.current?.close()}>Close Preview</button></section></dialog></>;}
export function DonationHistory(){const {data}=useAdminDemo();const donations=data.donations.filter(d=>d.email.toLowerCase()===demoDonor.email.toLowerCase());return <section className="account-panel donation-history-panel" aria-labelledby="history-heading"><div className="account-panel-heading history-heading"><span className="account-summary-icon"><FileText aria-hidden="true"/></span><div><p className="eyebrow">Your seva</p><h2 id="history-heading">Donation History</h2><p className="account-panel-subtitle">A record of your sample contributions.</p></div></div><div className="account-demo-notice account-history-notice"><span>DEMO RECORDS</span><p>These sample contributions are for preview only and are not stored in a donor database.</p></div><div className="account-donation-table-wrap"><table className="account-donation-table"><caption className="sr-only">Donor donation history</caption><thead><tr><th scope="col">Date</th><th scope="col">Donation For</th><th scope="col">Payment Method</th><th scope="col">Amount</th><th scope="col">Status</th><th scope="col">Receipt</th></tr></thead><tbody>{donations.map(donation=><tr key={donation.reference}><td>{formatDonationDate(donation.date)}</td><td><strong>{donation.givingFor}</strong><small>{donation.category}</small><small>{donation.reference}</small></td><td><PaymentBadge method={donation.method}/></td><td className="account-table-amount">{formatDonationAmount(donation.amountCents)}</td><td><StatusBadge status={donation.status}/></td><td>{donation.status==='Completed'?<ReceiptAction donation={donation}/>:<span className="receipt-unavailable">Unavailable</span>}</td></tr>)}</tbody></table></div><div className="account-donation-cards">{donations.map(donation=><article className="donation-history-card" key={donation.reference}><div className="donation-card-top"><div><p className="eyebrow">{formatDonationDate(donation.date)}</p><h3>{donation.givingFor}</h3></div><strong>{formatDonationAmount(donation.amountCents)}</strong></div><p className="donation-card-reference">{donation.category} · Reference <span>{donation.reference}</span></p><div className="donation-card-details"><div><span>Payment method</span><PaymentBadge method={donation.method}/></div><div><span>Status</span><StatusBadge status={donation.status}/></div></div><div className="donation-card-receipt">{donation.status==='Completed'?<ReceiptAction donation={donation}/>:<span className="receipt-unavailable">A receipt is not available for this donation.</span>}</div></article>)}</div><p className="account-history-footnote">Donation status and receipt details shown here are demonstration content.</p></section>;}
