'use client';
/* eslint-disable @typescript-eslint/no-unused-vars -- retained local donation helpers keep old browser data readable but are no longer rendered. */
import { useAdminDemo } from '../hooks/use-admin-demo';
import type { DonationCategory } from '../lib/donation-selection';
import { PageLink } from './page-link';

import { createContext, useContext, useRef, useState, type FormEvent, type ReactNode } from 'react';
import { usePathname, useRouter } from 'next/navigation';
import { LayoutDashboard, HandHeart, CalendarDays, ReceiptText, BarChart3, Menu, X, LogOut, ExternalLink, Search, Plus, Check, Info, Download, Users, Landmark, CircleDollarSign, ChevronRight } from 'lucide-react';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from './ui/dialog';
import {AuthRouteGuard} from './auth-route-guard';
import {useAuth} from './auth-provider';
import {LogoutLink} from './logout-link';
import {authErrorMessage} from '../lib/api-client';
import { Brand } from './ui';
import { FormInput, PasswordInput } from './auth-form';
import { CatalogManagement } from './admin-catalog';
import {RealAdminDashboard,RealAdminDonations,RealFinancialReports} from './admin-donations-real';
import { formatDonationAmount as money, formatDonationDate as date } from '../lib/account-demo';
import { createAdminState, createOfflineDonation, validateOfflineDonation, localDonationDate, offlineMethods, type OfflineDonationValues, donationTotals, filterDonations, donationCsv, emptyDonationFilters, type AdminState, type AdminDonation, type DonationFilters } from '../lib/admin-demo';
const navigation=[{href:'/admin',label:'Overview',icon:LayoutDashboard},{href:'/admin/giving',label:'Giving',icon:HandHeart},{href:'/admin/events',label:'Events',icon:CalendarDays},{href:'/admin/donations',label:'Donations',icon:ReceiptText},{href:'/admin/reports',label:'Reports',icon:BarChart3}];
type AdminContextValue={data:AdminState;setData:React.Dispatch<React.SetStateAction<AdminState>>;notify:(message:string)=>void};
const AdminContext=createContext<AdminContextValue|null>(null);
function useAdmin(){return useContext(AdminContext)!;}
function Badge({value}:{value:string}){return <span className={`adm-badge adm-${value.toLowerCase().replaceAll(' ','-')}`}>{value}</span>;}
function Notice({children}:{children:ReactNode}){return <p className="adm-notice"><Info aria-hidden="true"/>{children}</p>;}
function Action({children,onClick,secondary=false,danger=false,type='button',disabled=false}:{children:ReactNode;onClick?:()=>void;secondary?:boolean;danger?:boolean;type?:'button'|'submit';disabled?:boolean}){return <button type={type} disabled={disabled} onClick={onClick} className={`adm-button ${secondary?'adm-secondary':''} ${danger?'adm-danger':''}`}>{children}</button>;}
function Modal({title,description,children,onClose}:{title:string;description:string;children:ReactNode;onClose:()=>void}){return <Dialog open onOpenChange={open=>{if(!open)onClose();}}><DialogContent className="admin-modal" showCloseButton={false}><header><div><DialogTitle>{title}</DialogTitle><DialogDescription>{description}</DialogDescription></div><button className="adm-icon-button" onClick={onClose} aria-label="Close dialog"><X/></button></header>{children}</DialogContent></Dialog>;}
export function AdminShell({children}:{children:ReactNode}){
 const auth=useAuth();const path=usePathname();const {data,setData,storageFailed}=useAdminDemo();const [message,setMessage]=useState('');const [drawer,setDrawer]=useState(false);const [resetDemo,setResetDemo]=useState(false);
 const [previousPath,setPreviousPath]=useState(path);if(previousPath!==path){setPreviousPath(path);setDrawer(false);setMessage('');}
 const nav=<nav aria-label="Admin navigation">{navigation.map(({href,label,icon:Icon})=><PageLink key={href} href={href} className={path===href?'is-active':''} aria-current={path===href?'page':undefined}><Icon aria-hidden="true"/>{label}{path===href&&<ChevronRight className="adm-nav-chevron" aria-hidden="true"/>}</PageLink>)}</nav>;
 const footer=<div className="adm-sidebar-footer"><PageLink href="/"><ExternalLink aria-hidden="true"/>View public website</PageLink><LogoutLink admin><LogOut aria-hidden="true"/>Logout</LogoutLink><small>Pushthidham Haveli · Admin</small></div>;
 return <AdminContext.Provider value={{data,setData,notify:setMessage}}><div className="admin-app">{path==='/admin/login'?children:<AuthRouteGuard role="admin"><PageLink className="skip-link" href="#admin-main">Skip to admin content</PageLink><aside className="adm-sidebar"><Brand/><p className="adm-sidebar-label">TEMPLE ADMINISTRATION</p>{nav}{footer}</aside><div className="adm-workspace"><header className="adm-topbar"><button className="adm-icon-button adm-menu" aria-label="Open admin menu" onClick={()=>setDrawer(true)}><Menu/></button><span className="adm-topbar-title">{navigation.find(n=>n.href===path)?.label||'Administration'}</span><span className="adm-demo-pill">Backend API connected</span><PageLink className="adm-admin-user" href="/admin/login"><span>PH</span><div>{auth.user?.name}<small>{auth.user?.email} · {auth.user?.role}</small></div></PageLink></header><main id="admin-main" className="adm-main">{children}</main><footer className="adm-footer">© 2026 Pushthidham Haveli <span>Catalog, donations and financial reports are server-backed</span></footer></div>{drawer&&<Modal title="Admin navigation" description="Pushthidham Haveli administration" onClose={()=>setDrawer(false)}><div className="adm-mobile-nav">{nav}{footer}</div></Modal>}</AuthRouteGuard>}{message&&<div className="adm-toast" role="status"><Check aria-hidden="true"/><span>{message}</span><button className="adm-icon-button" aria-label="Dismiss notification" onClick={()=>setMessage('')}><X/></button></div>}</div></AdminContext.Provider>;
}
function PageHeading({title,description,children}:{title:string;description:string;children?:ReactNode}){return <div className="adm-page-heading"><div><p className="adm-eyebrow">PUSHTHIDHAM HAVELI</p><h1>{title}</h1><p>{description}</p></div>{children}</div>;}
function AdminLogin(){const auth=useAuth();const pendingRef=useRef(false);const [pending,setPending]=useState(false);const router=useRouter();const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [errors,setErrors]=useState<Record<string,string>>({});const form=useRef<HTMLFormElement>(null);async function submit(e:FormEvent){e.preventDefault();if(pendingRef.current)return;const next:Record<string,string>={};if(!email.trim())next.email='Please enter your email address.';else if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email.trim()))next.email='Please enter a valid email address.';if(!password)next.password='Please enter your password.';setErrors(next);const key=Object.keys(next)[0];if(key){form.current?.querySelector<HTMLElement>(`#admin-${key}`)?.focus();return;}pendingRef.current=true;setPending(true);try{const user=await auth.login(email.trim(),password);setPassword('');router.replace(user.role==='admin'?'/admin':'/account');}catch(error){setErrors({password:authErrorMessage(error)});}finally{pendingRef.current=false;setPending(false);}}return <div className="adm-login"><header><Brand/><PageLink href="/">Back to website</PageLink></header><div className="adm-login-card"><span className="adm-login-symbol"><Landmark/></span><p className="adm-eyebrow">TEMPLE ADMINISTRATION</p><h1>Admin Login</h1><p className="adm-login-subtitle">Manage seva, events and community giving.</p><form noValidate ref={form} onSubmit={submit}><FormInput id="admin-email" label="Email Address" value={email} type="email" onChange={setEmail} onBlur={()=>{}} autoComplete="username" error={errors.email}/><PasswordInput id="admin-password" label="Password" value={password} onChange={setPassword} onBlur={()=>{}} autoComplete="current-password" error={errors.password}/><Action type="submit" disabled={pending||auth.status==='initializing'}>{pending?'Signing in…':'Login'}</Action></form><Notice>Sign in with your temple administrator account. Dashboard data remains a local preview.</Notice></div><p className="adm-login-bottom">Seva · Bhakti · Sanskar</p></div>;}
function Stats({rows}:{rows:AdminDonation[]}){const totals=donationTotals(rows);const cards=[{label:'Total Donations',value:money(totals.total),detail:`${rows.length} donation records`,icon:CircleDollarSign},{label:'Average Donation',value:money(rows.length?Math.round(totals.total/rows.length):0),detail:'Average amount per donation · USD',icon:HandHeart},{label:'Total Donors',value:totals.donors.toString(),detail:'Unique donor email addresses',icon:Users}];return <div className="adm-stats">{cards.map(({label,value,detail,icon:Icon})=><section className="adm-stat" key={label}><div><span>{label}</span><Icon aria-hidden="true"/></div><strong>{value}</strong><small>{detail}</small></section>)}</div>;}
function DonationTable({rows,onView}:{rows:AdminDonation[];onView:(d:AdminDonation)=>void}){return rows.length?<div className="adm-table-wrap"><table className="adm-table adm-donations-table"><thead><tr>{['Reference / Date','Donor','Giving For','Amount','Payment Method','Action'].map(t=><th key={t} scope="col">{t}</th>)}</tr></thead><tbody>{rows.map(d=><tr key={d.reference}><td data-label="Reference / Date"><strong className="adm-reference">{d.reference}</strong><small>{date(d.date)}</small><small className="adm-donation-source">{d.source==='offline'?'Offline / Manual':'Online'}</small></td><td data-label="Donor"><strong>{d.donor}</strong><small>{d.email}</small></td><td data-label="Giving For"><strong>{d.givingFor}</strong><small className="adm-event-note">{d.category}{d.category==='Event'?` · ${d.eventId||d.eventSlug||''}`:''}</small></td><td data-label="Amount"><strong className="adm-amount">{money(d.amountCents)}</strong><small>USD · One-time</small></td><td data-label="Payment Method">{d.method}<small><Badge value={d.status}/></small></td><td className="adm-row-actions"><button className="adm-text-button" onClick={()=>onView(d)} aria-label={`View details ${d.reference}`}>View Details</button></td></tr>)}</tbody></table></div>:<div className="adm-empty"><ReceiptText/><h2>No donations found</h2><p>Try changing your search or filters.</p></div>;}
function DonationDetails({donation,onClose}:{donation:AdminDonation;onClose:()=>void}){const {data,setData,notify}=useAdmin();const current=data.donations.find(d=>d.reference===donation.reference)||donation;const [confirm,setConfirm]=useState<'Completed'|'Rejected'|null>(null);function change(){if(!confirm)return;setData(prev=>({...prev,donations:prev.donations.map(d=>d.reference===current.reference?{...d,status:confirm}:d)}));notify(`${current.reference} marked ${confirm.toLowerCase()} in this demo. No live record changed.`);setConfirm(null);}return <Modal title="Donation Details" description={current.reference} onClose={onClose}><div className="adm-detail-total"><div><small>Donation amount · USD</small><strong>{money(current.amountCents)}</strong></div><Badge value={current.status}/></div><dl className="adm-details">{[['Donor',current.donor],['Email',current.email],['Phone',current.phone||'Not provided'],[current.category==='Event'?'Event':'Giving For',current.givingFor],['Category',current.category],...(current.eventTitle?[['Supporting Event',current.eventTitle],['Event Identifier',current.eventSlug||'']]:[]),['Source',current.source==='offline'?'Offline / Manual':'Online'],...(current.adminNote?[['Admin Note',current.adminNote]]:[]),['Donation Type','One-Time'],['Payment Method',current.method],['Date',date(current.date)],['Transaction Reference',current.transactionReference||(current.source==='offline'?'Not provided':'Not applicable — PayPal demo')]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>{current.method==='Bank Transfer'&&current.status==='Pending'?(confirm?<div className="adm-confirm-box"><h3>{confirm==='Completed'?'Mark this donation completed?':'Reject this donation?'}</h3><p>{confirm==='Completed'?'In a live system, confirm the transfer against the bank statement first.':'This will mark the sample donation as rejected.'} This action updates local demo data only.</p><div className="adm-modal-actions"><Action secondary onClick={()=>setConfirm(null)}>Cancel</Action><Action danger={confirm==='Rejected'} onClick={change}>{confirm==='Completed'?'Confirm Completed':'Confirm Rejection'}</Action></div></div>:<><Notice>Bank transfers remain pending until checked against the bank statement. This demo does not verify real transfers.</Notice><div className="adm-modal-actions"><Action danger secondary onClick={()=>setConfirm('Rejected')}>Reject</Action><Action onClick={()=>setConfirm('Completed')}>Verify / Mark Completed</Action></div></>):<Notice>{current.method==='PayPal'?'PayPal donations do not require manual bank verification.':'This donation has already been reviewed in the demo.'} No payment or receipt is generated here.</Notice>}</Modal>;}
function Dashboard(){const {data}=useAdmin();const [selected,setSelected]=useState<AdminDonation|null>(null);const rows=filterDonations(data.donations,emptyDonationFilters);return <><PageHeading title="Admin Overview" description="A clear view of community giving and temple activities."/><Stats rows={data.donations}/><div className="adm-dashboard-strip"><div><Landmark/><div><strong>{data.giving.filter(g=>g.active).length} active giving opportunities</strong><span>{data.events.filter(e=>!e.past).length} upcoming events</span></div></div></div><section className="adm-surface"><div className="adm-section-heading"><div><h2>Recent Donations</h2><p>Latest offerings from our community</p></div><PageLink href="/admin/donations" className="adm-text-button">View all donations</PageLink></div><DonationTable rows={rows.slice(0,5)} onView={setSelected}/></section><section className="adm-quick-section"><h2>Quick Actions</h2><div className="adm-quick-grid">{[{href:'/admin/giving',title:'Manage Giving',copy:'Care for every seva opportunity',icon:HandHeart},{href:'/admin/events',title:'Manage Events',copy:'Organize devotional gatherings',icon:CalendarDays},{href:'/admin/reports',title:'Donation Reports',copy:'Review and export giving activity',icon:BarChart3}].map(({href,title,copy,icon:Icon})=><PageLink key={href} href={href}><Icon/><div><h3>{title}</h3><p>{copy}</p></div></PageLink>)}</div></section>{selected&&<DonationDetails donation={selected} onClose={()=>setSelected(null)}/>}</>;}
function SelectFilter({label,value,onChange,options}:{label:string;value:string;onChange:(value:string)=>void;options:string[]}){return <label className="adm-filter"><span>{label}</span><select value={value} onChange={e=>onChange(e.target.value)}>{options.map(v=><option key={v} value={v}>{v}</option>)}</select></label>;}
function DonationFilterBar({filters,setFilters,reports}:{filters:DonationFilters;setFilters:(f:DonationFilters)=>void;reports:boolean}){const update=(key:keyof DonationFilters,value:string)=>setFilters({...filters,[key]:value});return <div className="adm-filters">{!reports&&<label className="adm-filter adm-search"><span>Search donations</span><div><Search/><input type="search" value={filters.search} onChange={e=>update('search',e.target.value)} placeholder="Reference, donor or giving"/></div></label>}{reports&&<><label className="adm-filter"><span>From date</span><input type="date" value={filters.from} onChange={e=>update('from',e.target.value)}/></label><label className="adm-filter"><span>To date</span><input type="date" min={filters.from||undefined} value={filters.to} onChange={e=>update('to',e.target.value)}/></label></>}<SelectFilter label="Category" value={filters.category} onChange={v=>update('category',v)} options={['All','General','Event']}/><SelectFilter label="Status" value={filters.status} onChange={v=>update('status',v)} options={['All','Pending','Completed','Rejected']}/><SelectFilter label="Source" value={filters.source} onChange={v=>update('source',v)} options={['All','Online','Offline / Manual']}/><SelectFilter label="Payment method" value={filters.method} onChange={v=>update('method',v)} options={['All',...offlineMethods]}/><button className="adm-text-button adm-reset" onClick={()=>setFilters({...emptyDonationFilters})}>Reset filters</button></div>;}
function DonationManagement({reports=false}:{reports?:boolean}){const {data,notify}=useAdmin();const [filters,setFilters]=useState({...emptyDonationFilters});const [selected,setSelected]=useState<AdminDonation|null>(null);const [offline,setOffline]=useState(false);const rows=filterDonations(data.donations,filters);const invalidRange=!!(filters.from&&filters.to&&filters.from>filters.to);function exportCsv(){const blob=new Blob(['\uFEFF'+donationCsv(rows)],{type:'text/csv;charset=utf-8;'});const url=URL.createObjectURL(blob);const anchor=document.createElement('a');anchor.href=url;anchor.download='pushthidham-demo-donation-report.csv';anchor.click();URL.revokeObjectURL(url);notify(`CSV exported with ${rows.length} sample donation records.`);}return <><PageHeading title={reports?'Donation Reports':'Donations'} description={reports?'Review giving activity and export the filtered demo report.':'Review donor details and manage pending bank transfers.'}>{reports?<Action onClick={exportCsv}><Download/>Export CSV</Action>:<Action onClick={()=>setOffline(true)}><Plus/>Add Offline Donation</Action>}</PageHeading><section className="adm-surface"><DonationFilterBar filters={filters} setFilters={setFilters} reports={reports}/>{invalidRange&&<p className="adm-error" role="alert">Choose a to date on or after the from date.</p>}</section>{reports&&<Stats rows={rows}/>}<section className="adm-surface"><div className="adm-section-heading"><div><h2>{reports?'Donation Report':'Donation Records'}</h2><p>{rows.length} {rows.length===1?'record':'records'} · amounts in USD</p></div>{!reports&&<span className="adm-muted">Local demo data</span>}</div><DonationTable rows={rows} onView={setSelected}/></section>{offline&&<OfflineDonationEditor onClose={()=>setOffline(false)}/>} {selected&&<DonationDetails donation={selected} onClose={()=>setSelected(null)}/>}</>;}
export function AdminScreen({view}:{view:'login'|'dashboard'|'giving'|'events'|'donations'|'reports'}){if(view==='login')return <AdminLogin/>;if(view==='dashboard')return <RealAdminDashboard/>;if(view==='giving'||view==='events')return <CatalogManagement kind={view}/>;if(view==='donations')return <RealAdminDonations/>;return <RealFinancialReports/>;}

function OfflineDonationEditor({onClose}:{onClose:()=>void}){
  const {data,setData,notify}=useAdmin();
  const [values,setValues]=useState<OfflineDonationValues>(()=>{
    const giving=data.giving.find(g=>g.slug==='general-donation'&&g.active)||data.giving.find(g=>g.active);
    return {donor:'',email:'',phone:'',category:'General',givingSlug:giving?.slug||'',eventSlug:'',amount:'',method:'Cash',transactionReference:'',date:localDonationDate(),status:'Completed',adminNote:''};
  });
  const [errors,setErrors]=useState<Partial<Record<keyof OfflineDonationValues,string>>>({});
  const form=useRef<HTMLFormElement>(null);
  function update(key:keyof OfflineDonationValues,value:string){
    setValues(prev=>({...prev,[key]:key==='category'?value as DonationCategory:value,...(key==='category'?{givingSlug:value==='General'?(data.giving.find(g=>g.slug==='general-donation'&&g.active)||data.giving.find(g=>g.active))?.slug||'':'',eventSlug:value==='Event'?data.events[0]?.slug||'':''}:{}),...(key==='method'&&value==='Bank Transfer'?{status:'Pending'}:{})}));
  }
  function save(e:FormEvent){
    e.preventDefault();const next=validateOfflineDonation(data,values);setErrors(next);
    const first=Object.keys(next)[0];if(first){form.current?.querySelector<HTMLElement>(`#adm-offline-${first}`)?.focus();return;}
    const reference=`OFF-${values.date.replaceAll('-','')}-${crypto.randomUUID().slice(0,8).toUpperCase()}`;
    setData(prev=>({...prev,donations:[createOfflineDonation(prev,values,reference),...prev.donations]}));
    notify(`${reference} recorded as an offline donation in this demo. No payment was processed.`);onClose();
  }
  const fields:{key:keyof OfflineDonationValues;label:string;required?:boolean;type?:string;options?:{value:string;label:string}[];area?:boolean}[]=[
    {key:'donor',label:'Donor name',required:true},{key:'email',label:'Donor email',type:'email',required:true},{key:'phone',label:'Phone (optional)',type:'tel'},
    {key:'category',label:'Category',required:true,options:['General','Event'].map(value=>({value,label:value}))},
    ...(values.category==='General'?[{key:'givingSlug' as const,label:'Donation For',required:true,options:[{value:'',label:'Choose a giving item'},...data.giving.filter(g=>g.active).map(g=>({value:g.slug,label:g.title}))]}]:[{key:'eventSlug' as const,label:'Donation For',required:true,options:[{value:'',label:'Choose an event'},...data.events.map(e=>({value:e.slug,label:e.title+' — '+date(e.date)}))]}]),
    {key:'amount',label:'Amount (USD)',required:true},{key:'method',label:'Payment method',required:true,options:offlineMethods.map(value=>({value,label:value}))},
    {key:'transactionReference',label:'Payment / reference number',required:values.method!=='Cash'},{key:'date',label:'Donation date',type:'date',required:true},
    {key:'status',label:'Status',required:true,options:['Pending','Completed','Rejected'].map(value=>({value,label:value}))},{key:'adminNote',label:'Admin note (optional)',area:true},
  ];
  return <Modal title="Add Offline Donation" description="Record a manual donation in this browser’s demo. No payment or donor receipt is generated." onClose={onClose}><form ref={form} onSubmit={save} noValidate><div className="adm-editor-grid">{fields.map(field=>{
    const id=`adm-offline-${field.key}`;const error=errors[field.key];const props={id,value:values[field.key],onChange:(e:React.ChangeEvent<HTMLInputElement|HTMLSelectElement|HTMLTextAreaElement>)=>update(field.key,e.target.value),'aria-invalid':!!error,'aria-describedby':error?`${id}-error`:undefined};
    return <label className={`adm-field ${field.area?'adm-field-wide':''}`} key={field.key} htmlFor={id}><span>{field.label}{field.required?' *':''}</span>{field.options?<select {...props} required={field.required}>{field.options.map(option=><option key={option.value} value={option.value}>{option.label}</option>)}</select>:field.area?<textarea {...props} rows={3}/>:<input {...props} type={field.type||'text'} inputMode={field.key==='amount'?'decimal':undefined} max={field.key==='date'?localDonationDate():undefined} required={field.required}/>} {error&&<small id={`${id}-error`} className="adm-error">{error}</small>}</label>;
  })}</div><Notice>Record the actual amount received in USD. Bank transfers should stay Pending until verified by the temple.</Notice><div className="adm-modal-actions"><Action secondary onClick={onClose}>Cancel</Action><Action type="submit">Save Offline Donation</Action></div></form></Modal>;
}
