'use client';
import { useHydrated } from '../hooks/use-hydrated';

import { useRef, useState, type FormEvent } from 'react';
import {useRouter} from 'next/navigation';
import {loginDemo} from '../lib/demo-auth';
import { Eye, EyeOff, Check, Mail } from 'lucide-react';
import { authCopy, emptyAuthValues, passwordRequirements, validateAuth, type AuthMode, type AuthField } from '../lib/auth-ui';
type InputProps={id:string;label:string;value:string;onChange:(value:string)=>void;onBlur:()=>void;error?:string;autoComplete:string;optional?:boolean;type?:string;help?:string};
export function FormError({id,message}:{id:string;message?:string}){return message?<p className="auth-error" id={id}>{message}</p>:null;}
export function FormInput({id,label,value,onChange,onBlur,error,autoComplete,optional=false,type='text',help}:InputProps){return <div className="auth-field"><label htmlFor={id}>{label}{optional&&<span> (optional)</span>}</label><input id={id} name={id} type={type} autoComplete={autoComplete} required={!optional} value={value} onChange={e=>onChange(e.target.value)} onBlur={onBlur} aria-invalid={!!error} aria-describedby={[error?`${id}-error`:'',help?`${id}-help`:''].filter(Boolean).join(' ')||undefined}/>{help&&<p className="auth-help" id={`${id}-help`}>{help}</p>}<FormError id={`${id}-error`} message={error}/></div>;}
export function PasswordInput(props:InputProps){const [visible,setVisible]=useState(false);return <div className="auth-field"><label htmlFor={props.id}>{props.label}</label><div className={`auth-password ${props.error?'has-error':''}`}><input id={props.id} name={props.id} type={visible?'text':'password'} autoComplete={props.autoComplete} required value={props.value} onChange={e=>props.onChange(e.target.value)} onBlur={props.onBlur} aria-invalid={!!props.error} aria-describedby={[props.error?`${props.id}-error`:'',props.help&&!props.error?`${props.id}-help`:''].filter(Boolean).join(' ')||undefined}/><button type="button" aria-label={`${visible?'Hide':'Show'} ${props.label.toLowerCase()}`} aria-pressed={visible} aria-controls={props.id} onClick={()=>setVisible(!visible)}>{visible?<EyeOff aria-hidden="true"/>:<Eye aria-hidden="true"/>}</button></div>{props.help&&!props.error&&<p className="auth-help" id={`${props.id}-help`}>{props.help}</p>}<FormError id={`${props.id}-error`} message={props.error}/></div>;}
export function AuthButton({children}:{children:React.ReactNode}){return <button className="button auth-submit" type="submit">{children}</button>;}
function AuthResult({mode,onEdit}:{mode:AuthMode;onEdit:()=>void}){const ref=useRef<HTMLDivElement>(null);const hydrated=useHydrated();const next=hydrated?new URLSearchParams(window.location.search).get('returnTo'):null;const checkoutReturn=next?.startsWith('/checkout?')?next+'&donor=demo':null;const content={
login:{heading:'Login Preview',text:'Your form is ready. This demo does not verify credentials or create a signed-in session.'},
register:{heading:'Account Preview',text:'Your details meet the form requirements. No account has been created in this demo.'},
'forgot-password':{heading:'Reset Link Preview',text:'If an account exists for this email, password reset instructions will be sent once email services are connected.'},
'reset-password':{heading:'Password Reset Preview',text:'Your new password meets the form requirements. This demo has not changed any account password.'},
}[mode];return <div className="auth-result" role="status" tabIndex={-1} ref={node=>{ref.current=node;node?.focus();}}><span className="auth-result-icon">{mode==='forgot-password'?<Mail aria-hidden="true"/>:<Check aria-hidden="true"/>}</span><h2>{content.heading}</h2><p>{content.text}</p>{mode==='forgot-password'&&<p className="auth-help">No email has been sent.</p>}<div className="auth-result-actions">{mode==='forgot-password'?<a className="button" href="/reset-password">Preview Password Reset</a>:<button className="button" type="button" onClick={onEdit}>{mode==='login'?'Back to Login':mode==='register'?'Back to Create Account':'Edit Password'}</button>}{mode==='login'&&<a className="button auth-demo-account-link" href={checkoutReturn||"/account"}>{checkoutReturn?"Continue to Donation (Demo)":"Open Demo Account"}</a>}{mode!=='login'&&<a className="auth-text-link" href="/login">Back to Login</a>}</div></div>;}
export function AuthForm({mode}:{mode:AuthMode}){
const router=useRouter();const [loginError,setLoginError]=useState('');const [values,setValues]=useState({...emptyAuthValues});const [errors,setErrors]=useState<Partial<Record<AuthField,string>>>({});const [attempted,setAttempted]=useState(false);const [remember,setRemember]=useState(false);const [success,setSuccess]=useState(false);const hydrated=useHydrated();const loggedOut=hydrated&&mode==='login'&&new URLSearchParams(window.location.search).get('demo')==='logged-out';const form=useRef<HTMLFormElement>(null);const copy=authCopy[mode];
function change(field:AuthField,value:string){const next={...values,[field]:value};setValues(next);if(attempted)setErrors(validateAuth(mode,next));}
function blur(field:AuthField){if(values[field]||attempted)setErrors(prev=>({...prev,[field]:validateAuth(mode,values)[field]}));}
function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setLoginError('');setAttempted(true);const next=validateAuth(mode,values);setErrors(next);const first=Object.keys(next)[0];if(first){form.current?.querySelector<HTMLElement>(`#auth-${first}`)?.focus();return;}if(mode==='login'){const result=loginDemo('donor',values.email,values.password,remember);if(result!=='success'){setLoginError(result==='invalid'?'Incorrect demo email or password. Please try again.':'Browser storage is unavailable. Enable storage to use the demo account.');return;}setValues({...emptyAuthValues});router.push('/account');return;}setValues({...emptyAuthValues});setSuccess(true);}
function props(field:AuthField,label:string,autoComplete:string){return {id:`auth-${field}`,label,value:values[field],onChange:(value:string)=>change(field,value),onBlur:()=>blur(field),error:errors[field],autoComplete};}
return <><p className="eyebrow">Donor Account</p><h1 id="auth-title">{copy.title}</h1><p className="auth-subtitle">{copy.subtitle}</p>{loggedOut&&<p className="account-logout-message" role="status">You have signed out of the demo account.</p>}{success?<AuthResult mode={mode} onEdit={()=>{setSuccess(false);setErrors({});setAttempted(false);requestAnimationFrame(()=>form.current?.querySelector<HTMLInputElement>('input')?.focus());}}/>:<form ref={form} onSubmit={submit} noValidate className="auth-form"><div className={`auth-fields ${mode==='register'?'auth-register-fields':''}`}>{mode==='register'&&<><FormInput {...props('firstName','First Name','given-name')}/><FormInput {...props('lastName','Last Name','family-name')}/></>}{mode!=='reset-password'&&<div className="auth-full"><FormInput {...props('email','Email Address','email')} type="email"/></div>}{mode==='register'&&<div className="auth-full"><FormInput {...props('phone','Phone Number','tel')} type="tel" optional/></div>}{mode!=='forgot-password'&&<div className="auth-full"><PasswordInput {...props('password',mode==='reset-password'?'New Password':'Password',mode==='login'?'current-password':'new-password')} help={mode==='login'?undefined:passwordRequirements}/></div>}{(mode==='register'||mode==='reset-password')&&<div className="auth-full"><PasswordInput {...props('confirmPassword',mode==='reset-password'?'Confirm New Password':'Confirm Password','new-password')}/></div>}</div>{mode==='login'&&<div className="auth-login-options"><label className="auth-remember"><input type="checkbox" checked={remember} onChange={e=>setRemember(e.target.checked)}/><span>Remember Me</span></label><a className="auth-text-link" href="/forgot-password">Forgot Password?</a></div>}{loginError&&<p className="auth-error" role="alert">{loginError}</p>}<AuthButton>{copy.button}</AuthButton><p className="auth-demo-note">{mode==='login'?'Demo Mode — fixed test credentials only. No real authentication.':mode==='register'?'Demo only — no account is created or details saved.':mode==='forgot-password'?'Demo only — no reset email is sent.':'Demo only — no account password is changed.'}</p></form>}{!success&&<div className="auth-switch">{mode==='login'?<p>Don’t have an account? <a href="/register">Create Account</a></p>:mode==='register'?<p>Already have an account? <a href="/login">Login</a></p>:<a href="/login">Back to Login</a>}</div>}</>;}
