'use client';
import { useHydrated } from '../hooks/use-hydrated';

import { useRef, useState, type FormEvent } from 'react';
import {useRouter} from 'next/navigation';
import {useAuth} from './auth-provider';
import {ApiError,authErrorMessage} from '../lib/api-client';
import { Eye, EyeOff, Check, Mail } from 'lucide-react';
import { authCopy, emptyAuthValues, passwordRequirements, registrationPasswordRequirements, validateAuth, type AuthMode, type AuthField } from '../lib/auth-ui';
type InputProps={id:string;label:string;value:string;onChange:(value:string)=>void;onBlur:()=>void;error?:string;autoComplete:string;optional?:boolean;type?:string;help?:string};
export function FormError({id,message}:{id:string;message?:string}){return message?<p className="auth-error" id={id}>{message}</p>:null;}
export function FormInput({id,label,value,onChange,onBlur,error,autoComplete,optional=false,type='text',help}:InputProps){return <div className="auth-field"><label htmlFor={id}>{label}{optional&&<span> (optional)</span>}</label><input id={id} name={id} type={type} autoComplete={autoComplete} required={!optional} value={value} onChange={e=>onChange(e.target.value)} onBlur={onBlur} aria-invalid={!!error} aria-describedby={[error?`${id}-error`:'',help?`${id}-help`:''].filter(Boolean).join(' ')||undefined}/>{help&&<p className="auth-help" id={`${id}-help`}>{help}</p>}<FormError id={`${id}-error`} message={error}/></div>;}
export function PasswordInput(props:InputProps){const [visible,setVisible]=useState(false);return <div className="auth-field"><label htmlFor={props.id}>{props.label}</label><div className={`auth-password ${props.error?'has-error':''}`}><input id={props.id} name={props.id} type={visible?'text':'password'} autoComplete={props.autoComplete} required value={props.value} onChange={e=>props.onChange(e.target.value)} onBlur={props.onBlur} aria-invalid={!!props.error} aria-describedby={[props.error?`${props.id}-error`:'',props.help&&!props.error?`${props.id}-help`:''].filter(Boolean).join(' ')||undefined}/><button type="button" aria-label={`${visible?'Hide':'Show'} ${props.label.toLowerCase()}`} aria-pressed={visible} aria-controls={props.id} onClick={()=>setVisible(!visible)}>{visible?<EyeOff aria-hidden="true"/>:<Eye aria-hidden="true"/>}</button></div>{props.help&&!props.error&&<p className="auth-help" id={`${props.id}-help`}>{props.help}</p>}<FormError id={`${props.id}-error`} message={props.error}/></div>;}
export function AuthButton({children,disabled=false}:{children:React.ReactNode;disabled?:boolean}){return <button className="button auth-submit" type="submit" disabled={disabled}>{children}</button>;}
function AuthResult({mode,onEdit}:{mode:'forgot-password'|'reset-password';onEdit:()=>void}){const ref=useRef<HTMLDivElement>(null);const forgot=mode==='forgot-password';return <div className="auth-result" role="status" tabIndex={-1} ref={node=>{ref.current=node;node?.focus();}}><span className="auth-result-icon">{forgot?<Mail aria-hidden="true"/>:<Check aria-hidden="true"/>}</span><h2>{forgot?'Reset Link Preview':'Password Reset Preview'}</h2><p>{forgot?'If an account exists for this email, password reset instructions will be sent once email services are connected.':'Your new password meets the form requirements. This demo has not changed any account password.'}</p>{forgot&&<p className="auth-help">No email has been sent.</p>}<div className="auth-result-actions">{forgot?<a className="button" href="/reset-password">Preview Password Reset</a>:<button className="button" type="button" onClick={onEdit}>Edit Password</button>}<a className="auth-text-link" href="/login">Back to Login</a></div></div>;}
export function AuthForm({mode}:{mode:AuthMode}){
const router=useRouter();const [loginError,setLoginError]=useState('');const [values,setValues]=useState({...emptyAuthValues});const [errors,setErrors]=useState<Partial<Record<AuthField,string>>>({});const [attempted,setAttempted]=useState(false);const [remember,setRemember]=useState(false);const auth=useAuth();const pendingRef=useRef(false);const [pending,setPending]=useState(false);const [success,setSuccess]=useState(false);const hydrated=useHydrated();const loggedOut=hydrated&&mode==='login'&&new URLSearchParams(window.location.search).get('loggedOut')==='1';const form=useRef<HTMLFormElement>(null);const copy=authCopy[mode];
function change(field:AuthField,value:string){const next={...values,[field]:value};setValues(next);if(attempted)setErrors(validateAuth(mode,next));}
function blur(field:AuthField){if(values[field]||attempted)setErrors(prev=>({...prev,[field]:validateAuth(mode,values)[field]}));}
async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(pendingRef.current)return;setLoginError('');setAttempted(true);const next=validateAuth(mode,values);setErrors(next);const first=Object.keys(next)[0];if(first){form.current?.querySelector<HTMLElement>(`#auth-${first}`)?.focus();return;}
 if(mode==='login'||mode==='register'){pendingRef.current=true;setPending(true);try{const user=mode==='login'?await auth.login(values.email.trim(),values.password):await auth.register(`${values.firstName.trim()} ${values.lastName.trim()}`,values.email.trim(),values.password);setValues({...emptyAuthValues});const nextPath=new URLSearchParams(window.location.search).get('returnTo');const safeReturn=nextPath&&(nextPath==='/account'||nextPath.startsWith('/account/')||nextPath.startsWith('/checkout?'))?nextPath:null;router.replace(user.role==='admin'?'/admin':safeReturn||'/account');}catch(error){setLoginError(authErrorMessage(error));if(error instanceof ApiError&&error.details.length){const fieldMap:Record<string,AuthField>={name:'firstName',email:'email',password:'password'};const fields:Partial<Record<AuthField,string>>={};error.details.forEach(issue=>{const field=fieldMap[issue.path];if(field)fields[field]=issue.message;});setErrors(fields);}}finally{pendingRef.current=false;setPending(false);}return;}
 setValues({...emptyAuthValues});setSuccess(true);}

function props(field:AuthField,label:string,autoComplete:string){return {id:`auth-${field}`,label,value:values[field],onChange:(value:string)=>change(field,value),onBlur:()=>blur(field),error:errors[field],autoComplete};}
return <><p className="eyebrow">Donor Account</p><h1 id="auth-title">{copy.title}</h1><p className="auth-subtitle">{copy.subtitle}</p>{loggedOut&&<p className="account-logout-message" role="status">You have signed out.</p>}{success?<AuthResult mode={mode==='forgot-password'?'forgot-password':'reset-password'} onEdit={()=>{setSuccess(false);setErrors({});setAttempted(false);requestAnimationFrame(()=>form.current?.querySelector<HTMLInputElement>('input')?.focus());}}/>:<form ref={form} onSubmit={submit} noValidate className="auth-form"><div className={`auth-fields ${mode==='register'?'auth-register-fields':''}`}>{mode==='register'&&<><FormInput {...props('firstName','First Name','given-name')}/><FormInput {...props('lastName','Last Name','family-name')}/></>}{mode!=='reset-password'&&<div className="auth-full"><FormInput {...props('email','Email Address','email')} type="email"/></div>}{mode==='register'&&<div className="auth-full"><FormInput {...props('phone','Phone Number','tel')} type="tel" optional/></div>}{mode!=='forgot-password'&&<div className="auth-full"><PasswordInput {...props('password',mode==='reset-password'?'New Password':'Password',mode==='login'?'current-password':'new-password')} help={mode==='login'?undefined:mode==='register'?registrationPasswordRequirements:passwordRequirements}/></div>}{(mode==='register'||mode==='reset-password')&&<div className="auth-full"><PasswordInput {...props('confirmPassword',mode==='reset-password'?'Confirm New Password':'Confirm Password','new-password')}/></div>}</div>{mode==='login'&&<div className="auth-login-options"><label className="auth-remember"><input type="checkbox" checked={remember} onChange={e=>setRemember(e.target.checked)}/><span>Remember Me</span></label><a className="auth-text-link" href="/forgot-password">Forgot Password?</a></div>}{loginError&&<p className="auth-error" role="alert">{loginError}</p>}<AuthButton disabled={pending||auth.status==='initializing'}>{pending?'Please wait…':copy.button}</AuthButton><p className="auth-demo-note">{mode==='login'?'Your session is restored securely in this browser. Remember Me does not extend the server session.':mode==='register'?'Create a donor account. Phone details are not saved by account services yet.':mode==='forgot-password'?'Demo only — no reset email is sent.':'Demo only — no account password is changed.'}</p></form>}{!success&&<div className="auth-switch">{mode==='login'?<p>Don’t have an account? <a href="/register">Create Account</a></p>:mode==='register'?<p>Already have an account? <a href="/login">Login</a></p>:<a href="/login">Back to Login</a>}</div>}</>;}
