'use client';
import { useRef, useState, type FormEvent } from 'react';
import { MapPin, Phone, Mail, Clock3, HandHeart, Check, type LucideIcon } from 'lucide-react';
import { templeContact } from '../lib/contact';

export function ContactHero(){return <section className="about-page-hero contact-hero" aria-labelledby="contact-title"><img src={templeContact.image} alt="Haveli architectural artwork with domes and a tranquil garden"/><div className="about-page-hero-shade"/><div className="container about-page-hero-content"><h1 id="contact-title">Contact Us</h1><p>We would love to hear from you.</p></div></section>;}
function ContactCard({icon:Icon,title,children}:{icon:LucideIcon;title:string;children:React.ReactNode}){return <article className="contact-info-card"><span className="contact-icon"><Icon aria-hidden="true"/></span><div><h2>{title}</h2>{children}</div></article>;}
type Field = 'name'|'email'|'phone'|'subject'|'message';
type ContactValues = Record<Field,string>;
const initial:ContactValues={name:'',email:'',phone:'',subject:'',message:''};
function validate(values:ContactValues){const errors:Partial<Record<Field,string>>={};if(!values.name.trim())errors.name='Please enter your full name.';if(!values.email.trim())errors.email='Please enter your email address.';else if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(values.email.trim()))errors.email='Please enter a valid email address.';if(!values.subject.trim())errors.subject='Please enter a subject.';if(!values.message.trim())errors.message='Please enter your message.';return errors;}
export function ContactForm(){const [values,setValues]=useState<ContactValues>(initial);const [errors,setErrors]=useState<Partial<Record<Field,string>>>({});const [submitted,setSubmitted]=useState(false);const [success,setSuccess]=useState(false);const formRef=useRef<HTMLFormElement>(null);const successRef=useRef<HTMLDivElement>(null);
function update(field:Field,value:string){const next={...values,[field]:value};setValues(next);if(submitted)setErrors(validate(next));}
function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const next=validate(values);setErrors(next);setSubmitted(true);if(Object.keys(next).length){const first=Object.keys(next)[0];formRef.current?.querySelector<HTMLElement>(`[name="${first}"]`)?.focus();return;}setSuccess(true);requestAnimationFrame(()=>successRef.current?.focus());}
function field(field:Field,label:string,type='text',optional=false){return <div className="contact-field"><label htmlFor={`contact-${field}`}>{label}{optional?<span> (optional)</span>:<span aria-hidden="true"> *</span>}</label><input id={`contact-${field}`} name={field} type={type} autoComplete={field==='name'?'name':field==='email'?'email':field==='phone'?'tel':'off'} required={!optional} value={values[field]} maxLength={field==='subject'?150:200} onChange={e=>update(field,e.target.value)} onBlur={()=>{if(values[field]||submitted)setErrors(prev=>({...prev,[field]:validate(values)[field]}));}} aria-invalid={!!errors[field]} aria-describedby={errors[field]?`contact-${field}-error`:undefined}/>{errors[field]&&<p id={`contact-${field}-error`} className="contact-error">{errors[field]}</p>}</div>;}
return <section className="contact-form-panel" aria-labelledby="contact-form-title"><p className="eyebrow">Let’s connect</p><h2 id="contact-form-title">Send Us a Message</h2><p className="contact-form-intro">For darshan, seva or community enquiries, leave us a message.</p>{success?<div className="contact-success" ref={successRef} tabIndex={-1} role="status"><span className="contact-success-icon"><Check aria-hidden="true"/></span><h3>Thank You for Reaching Out</h3><p>Thank you for contacting us. This demo form is not yet connected to live email delivery.</p><p className="contact-success-note">Your message has not been sent or saved.</p><button className="button button-outline" onClick={()=>{setSuccess(false);setValues(initial);setErrors({});setSubmitted(false);requestAnimationFrame(()=>formRef.current?.querySelector<HTMLInputElement>('input')?.focus());}}>Write Another Message</button></div>:<form ref={formRef} onSubmit={submit} noValidate><p className="contact-required-note">* Required fields</p><div className="contact-fields">{field('name','Full Name')}{field('email','Email Address','email')}{field('phone','Phone Number','tel',true)}{field('subject','Subject')}<div className="contact-field contact-message"><label htmlFor="contact-message">Message <span aria-hidden="true">*</span></label><textarea id="contact-message" name="message" rows={5} maxLength={5000} required value={values.message} onChange={e=>update('message',e.target.value)} aria-invalid={!!errors.message} aria-describedby={errors.message?'contact-message-error':undefined}/>{errors.message&&<p id="contact-message-error" className="contact-error">{errors.message}</p>}</div></div><button className="button contact-send" type="submit">Send Message</button><p className="contact-demo-note">This demo form does not send email or store your message.</p></form>}</section>;}
export function ContactContent(){return <div className="container contact-content"><div className="contact-info-grid"><ContactCard icon={MapPin} title="Temple Address"><p>{templeContact.name}<br/>{templeContact.locality}</p><p className="contact-pending">{templeContact.address||templeContact.unconfirmed.address}</p></ContactCard><ContactCard icon={Phone} title="Phone">{templeContact.phone?<a href={`tel:${templeContact.phone}`}>{templeContact.phone}</a>:<p>{templeContact.unconfirmed.phone}</p>}</ContactCard><ContactCard icon={Mail} title="Email">{templeContact.email?<a href={`mailto:${templeContact.email}`}>{templeContact.email}</a>:<p>{templeContact.unconfirmed.email}</p>}</ContactCard><ContactCard icon={Clock3} title="Visiting / Temple Hours"><p>{templeContact.hours||templeContact.unconfirmed.hours}</p></ContactCard></div><div className="contact-main-grid"><ContactForm/><section className="contact-location" aria-labelledby="contact-location-title"><p className="eyebrow">A spiritual home</p><h2 id="contact-location-title">Visit the Haveli</h2><p>Come for darshan, connect with our community and share in the spirit of seva.</p><div className="contact-location-visual"><img src={templeContact.image} alt="Reference-inspired Haveli architectural artwork"/><div className="contact-location-caption"><MapPin aria-hidden="true"/><div><strong>{templeContact.name}</strong><span>{templeContact.locality}</span></div></div></div><div className="contact-location-note"><MapPin aria-hidden="true"/><p>The exact address and map will be available once the temple location is confirmed.</p></div>{templeContact.mapsUrl&&<a className="button button-outline" href={templeContact.mapsUrl}>Get Directions</a>}<div className="contact-welcome"><HandHeart aria-hidden="true"/><p>All are welcome at Pushthidham Haveli.</p></div></section></div></div>;}
