import { CalendarDays, Clock, MapPin, ChevronRight, HandHeart } from 'lucide-react';
import { eventDate, upcomingEvents, type TempleEvent } from '../lib/events';
import { EventCard } from './events';
import { Button, SectionHeading } from './ui';

export function EventMetadata({event}:{event:TempleEvent}) {
  return <div className="event-detail-meta"><span><CalendarDays aria-hidden="true"/><time dateTime={event.date}>{eventDate(event.date)}</time></span><span><Clock aria-hidden="true"/>{event.time} <abbr title="Eastern Time">ET</abbr></span><span><MapPin aria-hidden="true"/>{event.venue} · Ocala, Florida</span></div>;
}
export function EventSchedule({event}:{event:TempleEvent}) {
  return <section className="event-schedule" aria-labelledby="schedule-title"><p className="eyebrow">{event.past?'Celebration programme':'A day of devotion'}</p><h2 id="schedule-title">Event Schedule</h2><p className="schedule-timezone">All times Eastern Time</p><ol>{event.schedule.map(item=><li key={item.time}><span className="schedule-time">{item.time}</span><div><h3>{item.title}</h3><p>{item.description}</p></div></li>)}</ol></section>;
}
export function EventSupport({event}:{event:TempleEvent}) {
  return <section className="event-support" aria-labelledby="support-title"><HandHeart aria-hidden="true"/><h2 id="support-title">{event.past?'Keep Our Traditions Alive':'Support This Event'}</h2><p>Your generosity supports festival seva, prasadam and the celebrations that bring our community together.</p><Button href={`/giving?event=${encodeURIComponent(event.slug)}&opportunity=${event.kind==='annakut'?'annakut-mahotsav':'festival-sponsorship'}`}>Donate Now</Button></section>;
}
export function EventDetails({event}:{event:TempleEvent}) {
  const related = upcomingEvents.filter(other=>other.id!==event.id&&other.kind!==event.kind).slice(0,2);
  return <div className={`event-detail-page event-detail-${event.kind}`}><section className="event-detail-hero" aria-labelledby="detail-title"><img src={event.image} alt=""/><div className="event-detail-shade"/><div className="container event-detail-hero-copy"><p className="eyebrow">{event.past?'Past celebration':'Together in devotion'}</p><h1 id="detail-title">{event.title}</h1><EventMetadata event={event}/></div></section><nav className="container event-detail-breadcrumb" aria-label="Breadcrumb"><a href="/">Home</a><ChevronRight aria-hidden="true"/><a href="/events">Events</a><ChevronRight aria-hidden="true"/><span aria-current="page">{event.title}</span></nav><div className="container event-detail-body"><div className="event-detail-grid"><section className="event-information" aria-labelledby="information-title"><img className="event-detail-photo" src={event.image} alt={event.imageAlt}/><div className="event-information-copy">{event.past&&<span className="past-event-label">This event has taken place</span>}<p className="eyebrow">Seva · Bhakti · Community</p><h2 id="information-title">{event.title}</h2><EventMetadata event={event}/><p>{event.description}</p><p>{event.programme}</p><div className="event-welcome"><MapPin aria-hidden="true"/><div><h3>{event.venue}</h3><p>{event.location}</p><p>Families and visitors of all ages are warmly welcome. Please help us maintain a peaceful and respectful space for darshan.</p></div></div></div></section><aside className="event-detail-aside" aria-label="Programme and event support"><EventSchedule event={event}/><EventSupport event={event}/></aside></div><section className="event-related" aria-label="Upcoming Events"><div className="event-related-heading"><SectionHeading eyebrow="Continue celebrating together">Upcoming Events</SectionHeading><a href="/events" className="event-all-link">View all events</a></div><div className="events-list">{related.map(other=><EventCard key={other.id} event={other} past={false}/>)}</div></section></div></div>;
}
