'use client';
import {useRef} from 'react';
import {CalendarDays,Clock, X,Landmark as Church,HandHeart,HeartHandshake} from 'lucide-react';
import {Button,SectionHeading,icons} from './ui';
import {eventView,givingView,type GivingOpportunity,type TempleEvent} from '../lib/catalog-ui';
import {usePublicCatalog} from './catalog-provider';
export function HeroSection(){return <section className="hero" aria-labelledby="hero-title"><div className="hero-image"/><div className="hero-shade"/><div className="container hero-content"><p className="hero-welcome">Welcome to</p><h1 id="hero-title">Pushthidham Haveli</h1><p>A place of devotion, seva and community.</p><div className="hero-actions"><Button href="/donate">Donate Now</Button><Button href="#about" outline>Learn More</Button></div></div></section>}
export function QuickLinks(){return <div className="container quick-links">{[['give','Give','/donate'],['events','Upcoming Events','#events'],['seva','Seva Opportunities','/giving'],['temple','Visit Temple','#visit']].map(([icon,label,href])=>{const Icon=icons[icon as keyof typeof icons];return <a className="quick-card" href={href} key={label}><Icon aria-hidden="true"/><span>{label}</span></a>})}</div>}
export function EventCard({event}:{event:TempleEvent}){return <article className="event-card"><img src={event.image} alt={event.imageAlt}/><div className="event-copy"><p className="eyebrow">Festival & celebration</p><h3>{event.title}</h3><p className="event-meta"><span><CalendarDays size={17}/>{event.date.slice(0,10)}</span><span><Clock size={17}/>{event.time}</span></p><p>{event.shortDescription||event.description}</p><a className="button" href={event.detailsPath}>View Details</a></div></article>}
export function GivingCard({opportunity}:{opportunity:GivingOpportunity}){const title=opportunity.title;const description=opportunity.shortDescription;const Icon=icons[opportunity.icon];const dialog=useRef<HTMLDialogElement>(null);return <><article className="giving-card"><Icon aria-hidden="true"/><h3>{title}</h3><p>{description}</p><button className="giving-link" onClick={()=>dialog.current?.showModal()}>Explore this seva</button></article><dialog className="event-dialog" ref={dialog} aria-label={title} onClick={e=>{if(e.target===dialog.current)dialog.current.close()}}><section className="detail-panel"><button className="detail-close" aria-label="Close seva details" onClick={()=>dialog.current?.close()}><X/></button><p className="eyebrow">An offering from the heart</p><h2>{title}</h2><p>{description}</p><p>Offer your support through seva, festival participation and contributions to the Haveli. Your generosity helps keep our traditions alive for the whole community.</p><a className="button" href={`/donate?category=general&giving=${opportunity.slug}`} onClick={()=>dialog.current?.close()}>Donate</a></section></dialog></>}
export function HomeSections(){const {giving,events,loading,error}=usePublicCatalog();const opportunities=giving.slice(0,3).map(givingView);const featured=events.map(eventView).find(event=>!event.past)||events.map(eventView)[0];return <>{featured&&<section id="events" className="container events-section"><SectionHeading eyebrow="Together in devotion">Upcoming Event</SectionHeading><EventCard event={featured}/></section>}{!loading&&!featured&&!error&&<section id="events" className="container events-section"><SectionHeading eyebrow="Together in devotion">Upcoming Events</SectionHeading><p>New events will be announced soon.</p></section>}<section id="about" className="about-section"><div className="container about-grid"><div className="about-emblem" aria-hidden="true"><Church/><span>श्री कृष्ण शरणं मम</span><small>SHRI KRISHNA SHARANAM MAMA</small></div><div><SectionHeading eyebrow="Our faith. Our community.">Welcome to our spiritual home</SectionHeading><p>Pushthidham Haveli brings our community together through devotion to Shri Krishna, the joy of seva, and the traditions of Pushtimarg.</p><p>From daily darshan to festival celebrations, we nurture a welcoming space to connect, learn and serve.</p><div className="values"><span><Church/>Bhakti</span><span><HandHeart/>Seva</span><span><HeartHandshake/>Community</span></div></div></div></section><section id="giving" className="container giving-section"><SectionHeading eyebrow="An offering from the heart">Make a Meaningful Contribution</SectionHeading><p className="section-intro">Support temple seva, festivals and the community we share.</p>{loading?<p role="status">Loading giving opportunities…</p>:error?<p role="alert">{error}</p>:opportunities.length?<div className="giving-grid">{opportunities.map(item=><GivingCard key={item._id} opportunity={item}/>)}</div>:<p>No giving opportunities are currently available.</p>}<p id="giving-note" className="giving-note">Every act of seva is an offering of love. Discover a meaningful way to support the Haveli.</p></section><section className="quote-section"><p>“Seva, Bhakti and Sanskar for a Brighter Tomorrow”</p><span aria-hidden="true">❧</span></section></>}
