'use client';
import { PageLink } from './page-link';

import {useEffect,useRef,useState} from 'react';
import {usePathname} from 'next/navigation';
import { Menu, X, Home, CalendarDays, HandHeart, MapPin, UserRound, Landmark as Church } from 'lucide-react';
import {Brand,Button} from './ui';
const links=[['Home','/'],['About Us','/about'],['Events','/events'],['Donate / Giving','/giving'],['Contact Us','/contact']];
export function Header(){const pathname=usePathname();const [open,setOpen]=useState(false);const trigger=useRef<HTMLButtonElement>(null);const dialog=useRef<HTMLDialogElement>(null);
useEffect(()=>{if(open){dialog.current?.showModal();document.body.style.overflow='hidden'}else{dialog.current?.close();document.body.style.overflow=''}return()=>{document.body.style.overflow=''}},[open]);
function close(){setOpen(false);trigger.current?.focus()}
return <><header className="site-header"><div className="container header-inner"><Brand/><nav className="desktop-nav" aria-label="Main navigation">{links.map(([name,href])=><PageLink key={name} href={href} className={(name==='Home'&&pathname==='/')||(name==='About Us'&&pathname==='/about')||(name==='Events'&&(pathname==='/events'||pathname.startsWith('/events/')))||(name==='Donate / Giving'&&(pathname==='/giving'||pathname.startsWith('/giving/')||pathname==='/donate'||pathname==='/checkout'))||(name==='Contact Us'&&pathname==='/contact')?'active':''} aria-current={(name==='Home'&&pathname==='/')||(name==='About Us'&&pathname==='/about')||(name==='Events'&&(pathname==='/events'||pathname.startsWith('/events/')))||(name==='Donate / Giving'&&(pathname==='/giving'||pathname.startsWith('/giving/')||pathname==='/donate'||pathname==='/checkout'))||(name==='Contact Us'&&pathname==='/contact')?'page':undefined}>{name}</PageLink>)}</nav><Button href="/donate" className="header-donate">Donate Now</Button><button ref={trigger} className="menu-trigger" aria-label="Open menu" aria-expanded={open} onClick={()=>setOpen(true)}><Menu/></button></div></header><dialog ref={dialog} className="mobile-menu" onCancel={close} onClick={e=>{if(e.target===dialog.current)close()}}><div className="menu-panel"><div className="menu-top"><Brand/><button aria-label="Close menu" onClick={close}><X/></button></div><nav aria-label="Mobile navigation">{links.map(([name,href],i)=>{const Icon=[Home,Church,CalendarDays,HandHeart,MapPin][i];return <PageLink key={name} href={href} onClick={close}><Icon/>{name}</PageLink>})}<PageLink href="/login" onClick={close}><UserRound/>Donor Login</PageLink></nav><PageLink className="button button-outline" href="/donate" onClick={close}>Donate Now</PageLink><p className="menu-note">A place of devotion,<br/>seva and community.</p></div></dialog></>}
export function MobileBottomNav(){return <nav className="bottom-nav" aria-label="Quick navigation">{[['Home','/',Home],['Events','/events',CalendarDays],['Donate','/donate',HandHeart],['Visit','/contact',MapPin]].map(([label,href,Icon])=>{const I=Icon as typeof Home;return <PageLink key={String(label)} href={String(href)}><I aria-hidden="true"/><span>{String(label)}</span></PageLink>})}</nav>}
export function Footer(){return <footer className="site-footer" id="visit"><div className="container footer-grid"><div><Brand/><p>A place of devotion, seva and community.<br/>All are welcome at Pushthidham Haveli.</p></div><div><h3>Explore</h3><nav aria-label="Footer navigation">{links.map(([label,href])=><PageLink href={href} key={label}>{label}</PageLink>)}<PageLink href="/login">Donor Login</PageLink></nav></div><div><h3>Visit the Haveli</h3><p>Pushthidham Haveli<br/>Ocala, Florida, USA</p><p className="footer-small">Come for darshan.<br/>Stay connected through seva.</p></div></div><div className="container footer-bottom"><p>© {new Date().getFullYear()} Pushthidham Haveli</p><span>Seva, Bhakti and Sanskar</span></div></footer>}
