'use client';
import { useState, type FormEvent } from 'react';
import { Check, PencilLine, UserRound } from 'lucide-react';
import { AccountLayout } from '../../../components/account-layout';
import { FormInput } from '../../../components/auth-form';
import { demoDonor, type DemoDonor } from '../../../lib/account-demo';
type ProfileField='firstName'|'lastName'|'email'|'phone';
type ProfileErrors=Partial<Record<ProfileField,string>>;
function validate(values:DemoDonor):ProfileErrors{const errors:ProfileErrors={};if(!values.firstName.trim())errors.firstName='Please enter your first name.';if(!values.lastName.trim())errors.lastName='Please enter your last name.';if(!values.email.trim())errors.email='Please enter your email address.';else if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(values.email.trim()))errors.email='Please enter a valid email address.';return errors;}
export default function ProfilePage(){const [values,setValues]=useState({...demoDonor});const [editing,setEditing]=useState(false);const [attempted,setAttempted]=useState(false);const [errors,setErrors]=useState<ProfileErrors>({});const [notice,setNotice]=useState('');function update(field:ProfileField,value:string){const next={...values,[field]:value};setValues(next);if(attempted)setErrors(validate(next));}function props(field:ProfileField,label:string,autoComplete:string,type='text'){return{id:`profile-${field}`,label,value:values[field],onChange:(value:string)=>update(field,value),onBlur:()=>{if(values[field]||attempted)setErrors(prev=>({...prev,[field]:validate(values)[field]}));},error:errors[field],autoComplete,type,optional:field==='phone'};}function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setAttempted(true);const next=validate(values);setErrors(next);const first=Object.keys(next)[0] as ProfileField|undefined;if(first){document.getElementById(`profile-${first}`)?.focus();return;}setNotice('Profile changes are ready to be saved once account services are connected.');}function stopEditing(){setEditing(false);setAttempted(false);setErrors({});setNotice('');setValues({...demoDonor});}return <AccountLayout title="My Profile" description="Review the contact details shown in your donor account."><section className="account-panel profile-panel" aria-labelledby="profile-panel-title"><div className="account-panel-heading"><span className="account-summary-icon"><UserRound aria-hidden="true"/></span><div><p className="eyebrow">Donor details</p><h2 id="profile-panel-title">Profile Information</h2></div></div>{notice&&<div className="account-success" role="status"><Check aria-hidden="true"/><p>{notice}</p></div>}{!editing?<><dl className="profile-detail-list"><div><dt>First Name</dt><dd>{values.firstName}</dd></div><div><dt>Last Name</dt><dd>{values.lastName}</dd></div><div><dt>Email Address</dt><dd>{values.email}</dd></div><div><dt>Phone Number</dt><dd>{values.phone||'Not provided'}</dd></div></dl><button className="button profile-edit-button" onClick={()=>{setEditing(true);setNotice('');}}><PencilLine aria-hidden="true"/>Edit Profile</button></>:<form className="account-form" onSubmit={submit} noValidate><div className="account-profile-form-grid"><FormInput {...props('firstName','First Name','given-name')}/><FormInput {...props('lastName','Last Name','family-name')}/><div className="account-form-span"><FormInput {...props('email','Email Address','email','email')}/></div><div className="account-form-span"><FormInput {...props('phone','Phone Number','tel','tel')}/></div></div><p className="account-form-demo-note">Your changes will remain in this preview only and will not be saved.</p><div className="account-form-actions"><button className="button" type="submit">Save Changes</button><button className="account-cancel-button" type="button" onClick={stopEditing}>Cancel</button></div></form>}</section></AccountLayout>;}
