'use client';
import { useState, type FormEvent } from 'react';
import { Check, KeyRound } from 'lucide-react';
import { AccountLayout } from '../../../components/account-layout';
import { PasswordInput } from '../../../components/auth-form';
import { passwordRequirements } from '../../../lib/auth-ui';
type Field='currentPassword'|'newPassword'|'confirmPassword';
type Values=Record<Field,string>;
type Errors=Partial<Record<Field,string>>;
const initial:Values={currentPassword:'',newPassword:'',confirmPassword:''};
function validate(values:Values):Errors{const errors:Errors={};if(!values.currentPassword)errors.currentPassword='Please enter your current password.';if(!values.newPassword)errors.newPassword='Please enter a new password.';else if(values.newPassword.length<8||!/[a-zA-Z]/.test(values.newPassword)||!/[0-9]/.test(values.newPassword))errors.newPassword=passwordRequirements;else if(values.currentPassword&&values.newPassword===values.currentPassword)errors.newPassword='Choose a new password that differs from your current password.';if(!values.confirmPassword)errors.confirmPassword='Please confirm your new password.';else if(values.confirmPassword!==values.newPassword)errors.confirmPassword='Your passwords do not match.';return errors;}
export default function ChangePasswordPage(){const[values,setValues]=useState(initial);const[errors,setErrors]=useState<Errors>({});const[attempted,setAttempted]=useState(false);const[success,setSuccess]=useState(false);function update(field:Field,value:string){const next={...values,[field]:value};setValues(next);if(attempted)setErrors(validate(next));}function props(field:Field,label:string,autoComplete:string,help?:string){return{id:`account-${field}`,label,value:values[field],onChange:(value:string)=>update(field,value),onBlur:()=>{if(values[field]||attempted)setErrors(prev=>({...prev,[field]:validate(values)[field]}));},error:errors[field],autoComplete,help};}function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setAttempted(true);const next=validate(values);setErrors(next);const first=Object.keys(next)[0] as Field|undefined;if(first){document.getElementById(`account-${first}`)?.focus();return;}setValues(initial);setSuccess(true);}return <AccountLayout title="Change Password" description="Manage the password for your donor account preview."><section className="account-panel account-password-panel" aria-labelledby="change-password-title"><div className="account-panel-heading"><span className="account-summary-icon"><KeyRound aria-hidden="true"/></span><div><p className="eyebrow">Account security</p><h2 id="change-password-title">Change Password</h2></div></div><div className="account-demo-notice account-password-notice"><span>DEMO PREVIEW</span><p>This form checks your entries locally. It does not verify or change an account password.</p></div>{success&&<div className="account-success" role="status"><Check aria-hidden="true"/><p>Password change is ready for account services to be connected. No account password was changed.</p></div>}<form className="account-form account-password-form" onSubmit={submit} noValidate><PasswordInput {...props('currentPassword','Current Password','current-password')}/><PasswordInput {...props('newPassword','New Password','new-password',passwordRequirements)}/><PasswordInput {...props('confirmPassword','Confirm New Password','new-password')}/><p className="account-form-demo-note">Your password will not be saved in this demo.</p><button className="button account-password-submit" type="submit">Change Password</button></form></section></AccountLayout>;}
